# Generated by Django 4.2.18 on 2025-02-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
