# Generated by Django 4.2.18 on 2025-02-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='journal_type',
            new_name='type',
        ),
    ]
