# Generated by Django 4.2.18 on 2025-02-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_rename_journal_type_journal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
