# Generated by Django 4.2.18 on 2025-02-04 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0004_alter_journal_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='instructor',
        ),
        migrations.AddField(
            model_name='journal',
            name='instructor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
