# Generated by Django 5.1.7 on 2025-09-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_remove_journal_instructor_journal_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
