from django.contrib import admin
from .models import HighestActiveStudentCount, StudentChurnModelTrainingHistory, HighestRevenuePerStudent, HighestLifetimeInDaysPerStudent, StudentChurnPrediction

admin.site.register(HighestActiveStudentCount)
admin.site.register(StudentChurnModelTrainingHistory)
admin.site.register(HighestRevenuePerStudent)
admin.site.register(HighestLifetimeInDaysPerStudent)
admin.site.register(StudentChurnPrediction)