# Generated by Django 4.2.4 on 2023-08-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_address_1_alter_students_address_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='phone',
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24)),
                ('number_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.phonechoice')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.ManyToManyField(to='students.phone'),
        ),
    ]
