# Generated by Django 4.2.4 on 2023-08-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_phonechoice_remove_students_phone_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name_plural': 'Phone'},
        ),
        migrations.AlterModelOptions(
            name='phonechoice',
            options={'verbose_name_plural': 'Phone Choices'},
        ),
        migrations.AddField(
            model_name='phonechoice',
            name='name',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
