# Generated by Django 4.2.4 on 2024-01-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_phone_options_alter_phonechoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.ManyToManyField(blank=True, to='students.phone'),
        ),
    ]
