# Generated by Django 4.2.4 on 2024-01-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_phone_number_alter_students_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='date_time_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
