# Generated by Django 5.0.1 on 2024-04-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_students_date_time_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['last_name_romaji'], 'verbose_name_plural': 'Students'},
        ),
    ]
