# Generated by Django 5.1.7 on 2026-01-01 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0027_invoiceitem_tax_rate'),
        ('students', '0007_alter_students_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='payment_method_from_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.paymentmethod'),
        ),
    ]
