# Generated by Django 5.1.7 on 2026-01-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_students_payment_method_from_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='payment_method',
            new_name='payment_method_legacy',
        ),
    ]
