# Generated by Django 5.1.7 on 2025-10-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_invoiceitem_delete_eventtypefinancialprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypeFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Event Type Financial Profiles',
            },
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='event_type',
        ),
    ]
