# Generated by Django 5.1.7 on 2025-10-24 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_eventtypefinancialprofile_and_more'),
        ('schedule', '0015_eventtypefinancialprofile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTypeFinancialProfile',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.eventtype'),
        ),
    ]
