# Generated by Django 5.1.7 on 2025-10-24 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_eventtypefinancialprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
