# Generated by Django 5.1.7 on 2025-10-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_invoiceitem_delete_eventtypefinancialprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
