# Generated by Django 5.1.7 on 2025-10-24 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_invoiceitem_description'),
        ('students', '0007_alter_students_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(default=445, on_delete=django.db.models.deletion.CASCADE, to='students.students'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='year',
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.IntegerField(),
        ),
    ]
