# Generated by Django 5.1.7 on 2025-10-28 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_paymentmethod_tax_rename_price_invoiceitem_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoices.paymentmethod'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoices.tax'),
            preserve_default=False,
        ),
    ]
