# Generated by Django 5.1.7 on 2025-10-28 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoicetype_invoiceitem_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoicetype'),
            preserve_default=False,
        ),
    ]
