# Generated by Django 5.1.7 on 2025-10-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_alter_invoiceitem_invoice_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='invoice_type',
            new_name='service_type',
        ),
    ]
