# Generated by Django 5.1.7 on 2025-10-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_rename_invoice_type_invoiceitem_service_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceType',
            new_name='ServiceType',
        ),
    ]
