# Generated by Django 5.1.7 on 2025-10-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_rename_invoicetype_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='price',
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
    ]
