# Generated by Django 5.1.7 on 2025-10-28 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_servicetype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='tax',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoices.tax'),
            preserve_default=False,
        ),
    ]
