# Generated by Django 5.1.7 on 2025-10-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_servicetype_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name_plural': 'Service Types'},
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
