# Generated by Django 5.1.7 on 2025-11-19 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_invoice_customer_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
