# Generated by Django 5.1.7 on 2025-11-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_invoice_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
