# Generated by Django 5.1.7 on 2025-12-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_alter_invoice_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='default_value',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
