# Generated by Django 5.1.7 on 2025-12-30 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_invoice_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='tax',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoices.tax'),
            preserve_default=False,
        ),
    ]
