# Generated by Django 5.1.7 on 2025-12-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_remove_invoiceitem_tax_invoiceitem_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
