# Generated by Django 5.1.7 on 2025-12-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0026_invoice_issued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
