# Generated by Django 5.1.7 on 2026-03-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0028_alter_invoiceitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
