# Generated by Django 5.1.7 on 2026-05-02 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0030_revenuetype_servicetype_revenue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='revenue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.revenuetype'),
        ),
    ]
