# Generated by Django 5.1.7 on 2025-06-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighestActiveStudentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_student_count', models.PositiveIntegerField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Highest Active Student Count',
                'verbose_name_plural': 'Highest Active Student Counts',
            },
        ),
    ]
