# Generated by Django 5.1.7 on 2025-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_atriskstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentChurnModelTrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_accuracy', models.FloatField()),
                ('model_f1_score', models.FloatField()),
                ('model_precision', models.FloatField()),
                ('model_recall', models.FloatField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Student Churn Model Training History',
                'verbose_name_plural': 'Student Churn Model Training Histories',
            },
        ),
    ]
