# Generated by Django 5.1.7 on 2025-07-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_studentchurnmodeltraininghistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentchurnmodeltraininghistory',
            options={'verbose_name': 'Student Churn Model Training History', 'verbose_name_plural': 'Student Churn Model Training History'},
        ),
        migrations.AddField(
            model_name='studentchurnmodeltraininghistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
