# Generated by Django 5.1.7 on 2026-05-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_studentchurnmodeltraininghistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighestRevenuePerStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_per_student', models.FloatField()),
                ('value_type', models.CharField(choices=[('mean', 'Mean'), ('median', 'Median')], max_length=10)),
                ('date_time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Highest Revenue Per Student',
                'verbose_name_plural': 'Highest Revenue Per Students',
            },
        ),
    ]
