# Generated by Django 5.2.14 on 2026-07-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_highestlifetimeindaysperstudent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchurnmodeltraininghistory',
            name='active_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentchurnmodeltraininghistory',
            name='churned_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentchurnmodeltraininghistory',
            name='false_negatives',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentchurnmodeltraininghistory',
            name='false_positives',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentchurnmodeltraininghistory',
            name='feature_importance_absent_4_weeks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentchurnmodeltraininghistory',
            name='feature_importance_absent_8_weeks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentchurnmodeltraininghistory',
            name='feature_importance_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentchurnmodeltraininghistory',
            name='model_roc_auc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentchurnmodeltraininghistory',
            name='test_sample_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentchurnmodeltraininghistory',
            name='training_sample_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentchurnmodeltraininghistory',
            name='true_negatives',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentchurnmodeltraininghistory',
            name='true_positives',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AtRiskStudents',
        ),
    ]
