# Generated by Django 5.2.14 on 2026-07-28 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_studentchurnmodeltraininghistory_active_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='active_count',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='churned_count',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='false_negatives',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='false_positives',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='feature_importance_absent_4_weeks',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='feature_importance_absent_8_weeks',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='feature_importance_age',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='model_accuracy',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='model_f1_score',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='model_precision',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='model_recall',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='model_roc_auc',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='test_sample_size',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='training_sample_size',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='true_negatives',
        ),
        migrations.RemoveField(
            model_name='studentchurnmodeltraininghistory',
            name='true_positives',
        ),
    ]
