# Generated by Django 5.2.14 on 2026-07-29 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_remove_studentchurnmodeltraininghistory_active_count_and_more'),
        ('students', '0009_rename_payment_method_students_payment_method_legacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentChurnPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churn_prediction_probability', models.FloatField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
            options={
                'verbose_name': 'Student Churn Prediction',
                'verbose_name_plural': 'Student Churn Predictions',
            },
        ),
    ]
