# Generated by Django 5.2.14 on 2026-07-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_rename_churn_prediction_probability_studentchurnprediction_predicted_active_probability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentchurnprediction',
            old_name='predicted_active_probability',
            new_name='churn_probability',
        ),
    ]
