# Generated by Django 5.2.14 on 2026-09-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_rename_predicted_active_probability_studentchurnprediction_churn_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchurnprediction',
            name='trend',
            field=models.CharField(blank=True, choices=[('up', 'Up'), ('no_change', 'No Change'), ('down', 'Down')], default=None, max_length=10, null=True),
        ),
    ]
