# Generated by Django 5.0.1 on 2024-04-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_events_options_remove_events_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
