# Generated by Django 5.0.1 on 2024-04-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_events_date_time_created_events_date_time_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
