# Generated by Django 5.1.7 on 2025-10-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_eventtype_date_time_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='price',
        ),
    ]
