# Generated by Django 5.1.7 on 2025-10-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_remove_eventtype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
