# Generated by Django 5.1.7 on 2025-10-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('schedule', '0010_eventtype_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='financial_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.eventtypefinancialprofile'),
        ),
    ]
