# Generated by Django 5.1.7 on 2025-10-24 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_eventtypefinancialprofile_and_more'),
        ('schedule', '0013_alter_eventtype_financial_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='financial_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_types', to='invoices.eventtypefinancialprofile'),
        ),
    ]
