# Generated by Django 5.1.7 on 2025-10-24 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_eventtype_financial_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypeFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Event Type Financial Profiles',
            },
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='financial_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.eventtypefinancialprofile'),
        ),
    ]
