# Generated by Django 5.1.7 on 2025-10-24 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_eventtypefinancialprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='financial_profile',
        ),
    ]
