# Generated by Django 5.1.7 on 2025-10-24 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_remove_eventtype_financial_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='financial_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.eventtypefinancialprofile'),
        ),
    ]
