# Generated by Django 5.1.7 on 2025-10-24 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_eventtypefinancialprofile_and_more'),
        ('schedule', '0017_eventtype_financial_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='financial_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.eventtypefinancialprofile'),
        ),
        migrations.DeleteModel(
            name='EventTypeFinancialProfile',
        ),
    ]
