# Generated by Django 5.1.7 on 2025-10-24 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_remove_invoiceitem_invoice_delete_invoice_and_more'),
        ('schedule', '0019_remove_eventtype_financial_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='financial_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.eventtypefinancialprofile'),
        ),
    ]
