# Generated by Django 5.1.7 on 2025-10-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_eventtype_financial_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='financial_profile',
        ),
    ]
