# Generated by Django 5.1.7 on 2025-10-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_eventtypefinancialprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='financial_profile',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='price',
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
    ]
