# Generated by Django 5.1.7 on 2025-10-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_remove_eventtype_financial_profile_eventtype_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTypeFinancialProfile',
        ),
    ]
