# Generated by Django 5.1.7 on 2025-10-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_delete_eventtypefinancialprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='price',
        ),
    ]
