# Generated by Django 5.1.7 on 2025-10-28 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_rename_invoicetype_servicetype'),
        ('schedule', '0025_remove_eventtype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='invoice_service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoices.servicetype'),
            preserve_default=False,
        ),
    ]
