# Generated by Django 5.1.7 on 2025-10-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_eventtype_invoice_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='invoice_service_type',
        ),
    ]
