# Generated by Django 5.1.7 on 2025-10-28 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_servicetype_price'),
        ('schedule', '0027_remove_eventtype_invoice_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='invoice_service_type',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to='invoices.servicetype'),
            preserve_default=False,
        ),
    ]
