# Generated by Django 5.1.7 on 2026-03-26 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0006_alter_attendance_attendance_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_date', models.DateField()),
                ('warning_note', models.TextField(blank=True, null=True)),
                ('pending_date', models.DateField(blank=True, null=True)),
                ('pending_note', models.TextField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('resolved_note', models.TextField(blank=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance')),
            ],
        ),
    ]
