# Generated by Django 5.1.7 on 2026-03-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancealert',
            options={'verbose_name_plural': 'Attendance Alerts'},
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='date_time_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
