# Generated by Django 5.1.7 on 2025-04-22 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0007_alter_students_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardUUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_uuid', models.CharField(max_length=255, unique=True)),
                ('date_time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('linked_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
            options={
                'verbose_name_plural': 'Game Card UUIDs',
            },
        ),
    ]
