# Generated by Django 5.1.7 on 2025-05-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='Student',
            new_name='student',
        ),
    ]
