# Generated by Django 5.1.7 on 2025-05-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_student_checkin_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='attendance_present_count',
            field=models.IntegerField(default=0),
        ),
    ]
