# Generated by Django 5.0.1 on 2024-04-15 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name_romaji', models.CharField(blank=True, max_length=35, null=True)),
                ('first_name_romaji', models.CharField(blank=True, max_length=35, null=True)),
                ('last_name_katakana', models.CharField(blank=True, max_length=35, null=True)),
                ('first_name_katakana', models.CharField(blank=True, max_length=35, null=True)),
                ('last_name_kanji', models.CharField(blank=True, max_length=35, null=True)),
                ('first_name_kanji', models.CharField(blank=True, max_length=35, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
