# Generated by Django 5.0.1 on 2024-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_userprofilesinstructors_icon_stub'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilesinstructors',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
