# Generated by Django 5.0.1 on 2024-09-13 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_userprofilesinstructors_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilesinstructors',
            name='pref_attendance_selected_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pref_attendance_selected_instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
