# Generated by Django 4.1.3 on 2024-10-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_userprofilesinstructors_pref_attendance_selected_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilesinstructors',
            name='pref_attendance_selected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
