# Generated by Django 5.1.7 on 2025-04-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0007_alter_userprofilesinstructors_pref_attendance_selected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilesinstructors',
            name='pref_dashboard_working_days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
