# Generated by Django 5.2.14 on 2026-06-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0009_userprofilescustomers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilescustomers',
            name='first_name_kanji',
        ),
        migrations.RemoveField(
            model_name='userprofilescustomers',
            name='first_name_katakana',
        ),
        migrations.RemoveField(
            model_name='userprofilescustomers',
            name='first_name_romaji',
        ),
    ]
