# Generated by Django 5.2.14 on 2026-06-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_rename_payment_method_students_payment_method_legacy'),
        ('user_profiles', '0010_remove_userprofilescustomers_first_name_kanji_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofilescustomers',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='userprofilesinstructors',
            options={'verbose_name_plural': 'Instructors'},
        ),
        migrations.AddField(
            model_name='userprofilescustomers',
            name='related_students',
            field=models.ManyToManyField(blank=True, related_name='related_students', to='students.students'),
        ),
    ]
