# Generated by Django 5.2.14 on 2026-10-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0011_alter_userprofilescustomers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilesinstructors',
            name='attendance_notes_active',
            field=models.BooleanField(default=False),
        ),
    ]
