# Generated by Django 5.2.14 on 2026-10-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0012_userprofilesinstructors_attendance_notes_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilesinstructors',
            old_name='attendance_notes_active',
            new_name='attendance_record_notes_active',
        ),
    ]
