# Generated by Django 5.2.14 on 2026-10-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0013_rename_attendance_notes_active_userprofilesinstructors_attendance_record_notes_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilesinstructors',
            name='attendance_record_notes_active',
        ),
    ]
