# Generated by Django 5.1.7 on 2026-04-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='name_english',
        ),
        migrations.AddField(
            model_name='account',
            name='name_japanese',
            field=models.CharField(default='DEFAULT', max_length=255),
            preserve_default=False,
        ),
    ]
