# Generated by Django 5.1.7 on 2026-05-04 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_rename_name_account_name_english_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('EMPLOYEE', 'Employee')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalcontact'),
        ),
    ]
