# Generated by Django 5.1.7 on 2026-05-04 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_journalcontact_account_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='contact',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalcontact'),
        ),
    ]
