# Generated by Django 5.1.7 on 2026-05-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_account_contact_journalentry_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalcontact',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='journalcontact',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
