# Generated by Django 5.0.1 on 2024-09-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='date_time_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='date_time_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
