# Generated by Django 5.0.1 on 2024-11-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_date_time_created_and_more'),
        ('students', '0007_alter_students_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.gradechoices'),
        ),
    ]
