# Generated by Django 5.0.1 on 2024-11-11 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancerecord_grade'),
        ('students', '0007_alter_students_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='grade',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='students.gradechoices'),
        ),
    ]
