# Generated by Django 5.1.7 on 2025-05-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancerecord_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_records',
            field=models.ManyToManyField(blank=True, related_name='attendance_reverse_relationship', to='attendance.attendancerecord'),
        ),
    ]
