# Generated by Django 5.2.14 on 2026-10-03 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendancenote_attendancenotecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancenotecomment',
            name='linked_attendance_note',
        ),
        migrations.RemoveField(
            model_name='attendancenotecomment',
            name='linked_author',
        ),
        migrations.RemoveField(
            model_name='attendancenotecomment',
            name='linked_student',
        ),
        migrations.CreateModel(
            name='AttendanceRecordNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_note', models.TextField()),
                ('homework_note', models.TextField()),
                ('miscellaneous_note', models.TextField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('linked_attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancerecord')),
            ],
            options={
                'verbose_name_plural': 'Attendance Record Notes',
            },
        ),
        migrations.DeleteModel(
            name='AttendanceNote',
        ),
        migrations.DeleteModel(
            name='AttendanceNoteComment',
        ),
    ]
