# Generated by Django 5.2.14 on 2026-10-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_attendancenotecomment_linked_attendance_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecordnote',
            old_name='miscellaneous_note',
            new_name='general_note',
        ),
    ]
