# Generated by Django 5.2.14 on 2026-10-06 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_rename_miscellaneous_note_attendancerecordnote_general_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecordHomeworkNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_note', models.TextField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('linked_attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancerecord')),
            ],
            options={
                'verbose_name_plural': 'Attendance Record Homework Notes',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecordLessonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_note', models.TextField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('linked_attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancerecord')),
            ],
            options={
                'verbose_name_plural': 'Attendance Record Lesson Notes',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecordStudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_note', models.TextField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('linked_attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancerecord')),
            ],
            options={
                'verbose_name_plural': 'Attendance Record Student Notes',
            },
        ),
        migrations.DeleteModel(
            name='AttendanceRecordNote',
        ),
    ]
