# Generated by Django 5.2.14 on 2026-10-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendancerecordhomeworknote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecordstudentnote',
            old_name='general_note',
            new_name='student_note',
        ),
    ]
