# Generated by Django 5.2.14 on 2026-10-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_rename_general_note_attendancerecordstudentnote_student_note'),
        ('students', '0009_rename_payment_method_students_payment_method_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecordhomeworknote',
            name='linked_student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='students.students'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerecordlessonnote',
            name='linked_student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='students.students'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerecordstudentnote',
            name='linked_student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='students.students'),
            preserve_default=False,
        ),
    ]
