# Generated by Django 5.2.14 on 2026-10-07 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendancerecordhomeworknote_linked_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecordhomeworknote',
            name='linked_attendance_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework_note_obj', to='attendance.attendancerecord'),
        ),
        migrations.AlterField(
            model_name='attendancerecordlessonnote',
            name='linked_attendance_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_note_obj', to='attendance.attendancerecord'),
        ),
        migrations.AlterField(
            model_name='attendancerecordstudentnote',
            name='linked_attendance_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_note_obj', to='attendance.attendancerecord'),
        ),
    ]
